/** Near-term catalog (2026–2028). Expand as needed. */
export const ECLIPSE_CATALOG: EclipseEvent[] = (
  [
  {
    id: "se-2026-02-17-annular",
    kind: "solar",
    type: "annular",
    name: "Annular solar eclipse",
    peakMs: utc(2026, 2, 17, 12, 12),
    peakLabel: "2026-02-17 ~12:12 UTC",
    watchStartMs: utc(2026, 2, 10),
    watchEndMs: utc(2026, 2, 18, 23),
    path: "Annular path mainly Antarctica; partial over southern Chile/Argentina & southern Africa.",
    regions: "Antarctica · southern tip of South America · southern Africa (partial)",
    nasaUrl: "https://science.nasa.gov/eclipses/future-eclipses/",
    mapUrl: "https://www.timeanddate.com/eclipse/solar/2026-february-17",
    syzygy: "new",
    safety: "Solar — certified eclipse glasses required for any partial phases.",
    note: "Ring of fire for path of annularity only.",
  },
  {
    id: "le-2026-03-03-total",
    kind: "lunar",
    type: "total",
    name: "Total lunar eclipse",
    peakMs: utc(2026, 3, 3, 11, 34),
    peakLabel: "2026-03-03 ~11:34 UTC",
    watchStartMs: utc(2026, 2, 28),
    watchEndMs: utc(2026, 3, 4, 12),
    path: "Totality visible across much of the Americas; Asia/Australia also see stages.",
    regions: "Americas · Europe (partial) · Asia · Australia · Pacific",
    nasaUrl: "https://science.nasa.gov/eclipses/future-eclipses/",
    mapUrl: "https://www.timeanddate.com/eclipse/lunar/2026-march-3",
    syzygy: "full",
    safety: "Lunar — safe to view with unaided eyes (no solar filter).",
    note: "Full-moon total eclipse · blood-moon appearance possible in totality.",
  },
  {
    id: "se-2026-08-12-total",
    kind: "solar",
    type: "total",
    name: "Total solar eclipse",
    peakMs: utc(2026, 8, 12, 17, 47),
    peakLabel: "2026-08-12 ~17:47 UTC",
    watchStartMs: utc(2026, 8, 1),
    watchEndMs: utc(2026, 8, 13, 6),
    path: "Totality: Greenland · Iceland · Spain (and a thin corridor). Partial: most of Europe, N. Africa, parts of N. America.",
    regions: "Greenland · Iceland · Spain (total) · Europe · N. Africa · N. America (partial)",
    nasaUrl:
      "https://science.nasa.gov/eclipses/future-eclipses/total-solar-eclipse-on-august-12-2026/",
    mapUrl: "https://www.timeanddate.com/eclipse/solar/2026-august-12",
    syzygy: "new",
    safety:
      "Solar — never look at the Sun without ISO-certified eclipse glasses except during totality only (if in path).",
    note: "First total solar over western/central Europe since 1999 for many observers.",
  },
  {
    id: "le-2026-08-28-partial",
    kind: "lunar",
    type: "partial",
    name: "Partial lunar eclipse",
    peakMs: utc(2026, 8, 28, 4, 13),
    peakLabel: "2026-08-28 ~04:13 UTC",
    watchStartMs: utc(2026, 8, 25),
    watchEndMs: utc(2026, 8, 29),
    path: "Partial stages over Americas, Europe, Africa.",
    regions: "Americas · Europe · Africa · Atlantic",
    nasaUrl: "https://science.nasa.gov/eclipses/future-eclipses/",
    mapUrl: "https://www.timeanddate.com/eclipse/lunar/2026-august-28",
    syzygy: "full",
    safety: "Lunar — safe unaided.",
    note: "Companion lunar eclipse ~2 weeks after Aug 12 total solar (eclipse season).",
  },
  {
    id: "se-2027-02-06-annular",
    kind: "solar",
    type: "annular",
    name: "Annular solar eclipse",
    peakMs: utc(2027, 2, 6, 16, 0),
    peakLabel: "2027-02-06 ~16:00 UTC",
    watchStartMs: utc(2027, 1, 30),
    watchEndMs: utc(2027, 2, 7, 23),
    path: "Annularity: South America & West Africa corridor.",
    regions: "Chile · Argentina · Uruguay · Brazil · West Africa (annular/partial)",
    nasaUrl: "https://science.nasa.gov/eclipses/future-eclipses/",
    mapUrl: "https://www.timeanddate.com/eclipse/solar/2027-february-6",
    syzygy: "new",
    safety: "Solar — certified eclipse glasses required outside annularity path rules.",
    note: "Ring of fire over South Atlantic / Africa–America path.",
  },
  {
    id: "le-2027-02-20-penumbral",
    kind: "lunar",
    type: "penumbral",
    name: "Penumbral lunar eclipse",
    peakMs: utc(2027, 2, 20, 23, 13),
    peakLabel: "2027-02-20 ~23:13 UTC",
    watchStartMs: utc(2027, 2, 18),
    watchEndMs: utc(2027, 2, 21, 12),
    path: "Subtle penumbral shading — wide Earth visibility.",
    regions: "Americas · Europe · Africa · Asia · Australia",
    nasaUrl: "https://science.nasa.gov/eclipses/future-eclipses/",
    mapUrl: "https://www.timeanddate.com/eclipse/lunar/2027-february-20",
    syzygy: "full",
    safety: "Lunar — safe unaided; shading may be faint.",
    note: "Penumbral only — low visual drama, still real geometry.",
  },
  {
    id: "se-2027-08-02-total",
    kind: "solar",
    type: "total",
    name: "Total solar eclipse",
    peakMs: utc(2027, 8, 2, 10, 7),
    peakLabel: "2027-08-02 ~10:07 UTC",
    watchStartMs: utc(2027, 7, 20),
    watchEndMs: utc(2027, 8, 3, 6),
    path: "Long totality across N. Africa / Mediterranean / Arabia.",
    regions: "Spain (south) · Morocco · Algeria · Tunisia · Libya · Egypt · Saudi · Yemen",
    nasaUrl: "https://science.nasa.gov/eclipses/future-eclipses/",
    mapUrl: "https://www.timeanddate.com/eclipse/solar/2027-august-2",
    syzygy: "new",
    safety: "Solar — glasses required for all partial phases.",
    note: "One of the longer totalities of the decade along the African path.",
  },
] satisfies EclipseEvent[]
).slice().sort((a, b) => a.peakMs - b.peakMs);
